language: python
python:
- '2.7'
install:
- pip install requests
script:
- python movie.py
before_install:
- openssl aes-256-cbc -K $encrypted_c730c308b3de_key -iv $encrypted_c730c308b3de_iv
  -in movie_api_key.enc -out movie_api_key -d
